### ISSUE TITLE
Don't try to install a Node version that's already installed

### ISSUE THREAD

**Issue by calavera** [netlify/build-image#180] opened 2018-07-02 03:58 UTC
If we load a version from the cache, and it's the same version is specified in `.nvmrc` or `.node-version`, we should not run `nvm install`. This will prevent from pinging nodejs.org when it's not necessary.

/cc @fool

**Comment by brycekahle** [comment] 2018-07-31 19:52
`nvm` will use the already installed version, if available: https://github.com/creationix/nvm/blob/17c33fd9aeb42261d38fea676246700898ea2855/nvm.sh#L2722

Is there something else you were trying to prevent?

**Comment by fool** [comment] 2018-07-31 20:57
I understand that nvm intends to do this, but in practice, when node's CDN
was down, it didn't work like that: those builds that re-used a node
version that should have been cached, failed because the CDN was
unreachable despite the same node version already being in our cache.

**Comment by brycekahle** [comment] 2018-07-31 21:00
@fool Can you link me to build logs that I can study?

**Comment by fool** [comment] 2018-07-31 21:42
unable to reproduce, closing.

I tested:

- set in UI only
- set in toml only
- set in UI + toml differently
- set in UI + toml same

all showed the command somewhere.  It isn't all in the "same place" - some nearer the top of the deploy and some kinda in the middle - but it's always there and that's good enough for me.

**Comment by brycekahle** [comment] 2018-08-01 11:58
@fool I think you posted to the wrong issue. I believe you meant #166

**Comment by bcomnes** [comment] 2019-02-16 01:44
Is this still happening?  Someone will need to reproduce at this point.

**Comment by rybit** [comment] 2019-02-18 18:41
Closing b/c we haven’t seen repro in 7months

**Closed by rybit** 2019-02-18 18:41 UTC
Labels: enhancement, medium-priority, needs-reproduction
