### ISSUE TITLE
build of dependencies fails on ruby 

### ISSUE THREAD

**Issue by memocenose** [netlify/build-image#626] opened 2021-09-16 06:57 UTC
im trying to migrate from old image switching to focal image for my Hugo based site.
So far it fails on some ruby dependencies. Is it possible to disable installation of javascript and ruby in netlify.toml ?

**Comment by memocenose** [comment] 2021-09-16 07:06
8:51:16 AM: Build ready to start
8:51:17 AM: build-image version: fa439ad1ab9393b2c0d449d8d7c033927683f4b0
8:51:17 AM: build-image tag: v4.3.0
8:51:17 AM: buildbot version: e99637385725adf30662bad8cf7d70d9f3623653
8:51:17 AM: Building without cache
8:51:17 AM: Starting to prepare the repo for build
8:51:18 AM: No cached dependencies found. Cloning fresh repo
8:51:18 AM: git clone https://github.com/memocenose/memocenose.com
8:51:18 AM: Preparing Git Reference refs/heads/master
8:51:19 AM: Parsing package.json dependencies
8:51:19 AM: Starting build script
8:51:19 AM: Installing dependencies
8:51:19 AM: Python version set to 2.7
8:51:20 AM: Downloading and installing node v8.17.0...
8:51:20 AM: Downloading https://nodejs.org/dist/v8.17.0/node-v8.17.0-linux-x64.tar.xz...
8:51:20 AM: Computing checksum with sha256sum
8:51:20 AM: Checksums matched!
8:51:22 AM: Now using node v8.17.0 (npm v6.13.4)
8:51:22 AM: Started restoring cached build plugins
8:51:22 AM: Finished restoring cached build plugins
8:51:22 AM: Attempting ruby version 2.3.6, read from environment
8:51:23 AM: Required ruby-2.3.6 is not installed - installing.
8:51:24 AM: Searching for binary rubies, this might take some time.
8:51:24 AM: Found remote file https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/20.04/x86_64/ruby-2.3.6.tar.bz2
8:51:24 AM: Checking requirements for ubuntu.
8:51:24 AM: Missing required packages: libssl1.0-dev
8:51:24 AM: RVM autolibs is now configured with mode '2' =>
8:51:24 AM:   'Allow RVM to use package manager if found, fail if dependencies are missing. This is default.',
8:51:24 AM: please run `rvm autolibs enable` to let RVM do its job or run and read `rvm autolibs [help]`
8:51:24 AM: or visit https://rvm.io/rvm/autolibs for more information.
8:51:24 AM: Found undesired packages: libssl-dev
8:51:24 AM: RVM autolibs is now configured with mode '2' =>
8:51:24 AM:   'Allow RVM to use package manager if found, fail if dependencies are missing. This is default.',
8:51:24 AM: please run `rvm autolibs enable` to let RVM do its job or run and read `rvm autolibs [help]`
8:51:24 AM: or visit https://rvm.io/rvm/autolibs for more information.
8:51:24 AM: Requirements installation failed with status: 1.
8:51:24 AM: ruby-2.3.6 - #gemset created /opt/buildhome/.rvm/gems/ruby-2.3.6
8:51:24 AM: Required ruby-2.3.6 is not installed - installing.
8:51:25 AM: Searching for binary rubies, this might take some time.
8:51:25 AM: Found remote file https://rvm_io.global.ssl.fastly.net/binaries/ubuntu/20.04/x86_64/ruby-2.3.6.tar.bz2
8:51:25 AM: Checking requirements for ubuntu.
8:51:25 AM: Missing required packages: libssl1.0-dev
8:51:25 AM: RVM autolibs is now configured with mode '2' =>
8:51:26 AM:   'Allow RVM to use package manager if found, fail if dependencies are missing. This is default.',
8:51:26 AM: please run `rvm autolibs enable` to let RVM do its job or run and read `rvm autolibs [help]`
8:51:26 AM: or visit https://rvm.io/rvm/autolibs for more information.
8:51:26 AM: Found undesired packages: libssl-dev
8:51:26 AM: RVM autolibs is now configured with mode '2' =>
8:51:26 AM:   'Allow RVM to use package manager if found, fail if dependencies are missing. This is default.',
8:51:26 AM: please run `rvm autolibs enable` to let RVM do its job or run and read `rvm autolibs [help]`
8:51:26 AM: or visit https://rvm.io/rvm/autolibs for more information.
8:51:26 AM: Requirements installation failed with status: 1.
8:51:26 AM: ruby-2.3.6 - #importing gemsetfile /opt/buildhome/.rvm/gemsets/default.gems evaluated to empty gem list
8:51:26 AM: ruby-2.3.6 - #generating default wrappers.................
8:51:26 AM: Error running 'run_gem_wrappers regenerate',
8:51:26 AM: please read /opt/buildhome/.rvm/log/1631775086_ruby-2.3.6/gemset.wrappers.default.log
8:51:26 AM: Using /opt/buildhome/.rvm/gems/ruby-2.3.6
8:51:26 AM: Warning! Executable 'ruby' missing, something went wrong with this ruby installation!
8:51:26 AM: Warning! Executable 'gem' missing, something went wrong with this ruby installation!
8:51:26 AM: Warning! Executable 'irb' missing, something went wrong with this ruby installation!
8:51:26 AM: Using ruby version 2.3.6
8:51:26 AM: /opt/buildhome/.rvm/scripts/override_gem: line 19: gem: command not found
8:51:26 AM: Error installing bundler
8:51:26 AM: Build was terminated: Build script returned non-zero exit code: 1
8:51:26 AM: Creating deploy upload records
8:51:26 AM: Failing build: Failed to build site
8:51:26 AM: Failed during stage 'building site': Build script returned non-zero exit code: 1
8:51:26 AM: Finished processing build request in 8.843811352s

**Comment by JGAntunes** [comment] 2021-09-16 17:58
Hey @memocenose 👋 thanks for raising this. From what you've just described seems like this is a duplicate of #599.

As described in https://github.com/netlify/build-image/issues/599#issuecomment-920038722 we're currently working on a fix to address the `Ruby 2.3.6` compatibility issues for anyone upgrading to Focal. Meanwhile though, if you want to upgrade you can either re-link your repo or set a higher `RUBY_VERSION` (see [here](https://answers.netlify.com/t/please-read-end-of-support-for-trusty-build-image-everything-you-need-to-know/39004#how-can-i-make-my-site-work-with-the-new-image-6), under the point `3.` on how to perform either).

Going to close this and we can follow up in #599 if needed.

**Closed as completed by JGAntunes** 2021-09-16 17:58 UTC
