### ISSUE TITLE
Yarn install runs even when a node_modules cache is found

### ISSUE THREAD

**Issue by jlengstorf** [netlify/build-image#433] opened 2020-05-20 21:04 UTC
Thanks for reporting this bug!

I could have sworn we already had an issue open for this, but I can't find it. Filing here so I can link when people hit this.

**Describe the bug**

The build will restore `node_modules` successfully, but when a `yarn.lock` file is present it re-runs the `yarn` command and reinstalls all packages anyways.

Here's an excerpt of a log from [this community issue](https://community.netlify.com/t/incremental-gatsby-build-time-increases/14722) that shows the unnecessary install happening and adding almost 4 minutes to the build:

```
8:06:33 PM: Started restoring cached node modules
8:06:33 PM: Finished restoring cached node modules
8:06:33 PM: Started restoring cached yarn cache
8:06:33 PM: Finished restoring cached yarn cache
8:06:34 PM: Installing NPM modules using Yarn version 1.17.0
8:06:35 PM: yarn install v1.17.0
8:06:35 PM: [1/4] Resolving packages...
8:06:37 PM: [2/4] Fetching packages...
8:07:59 PM: info fsevents@2.1.2: The platform "linux" is incompatible with this module.
8:07:59 PM: info "fsevents@2.1.2" is an optional dependency and failed compatibility check. Excluding it from installation.
8:07:59 PM: info fsevents@1.2.11: The platform "linux" is incompatible with this module.
8:07:59 PM: info "fsevents@1.2.11" is an optional dependency and failed compatibility check. Excluding it from installation.
8:07:59 PM: info fsevents@2.0.6: The platform "linux" is incompatible with this module.
8:07:59 PM: info "fsevents@2.0.6" is an optional dependency and failed compatibility check. Excluding it from installation.
8:07:59 PM: [3/4] Linking dependencies...
8:07:59 PM: warning " > @crello/react-lottie@0.0.7" has incorrect peer dependency "react@~16.9.0".
8:07:59 PM: warning " > @crello/react-lottie@0.0.7" has incorrect peer dependency "react-dom@~16.9.0".
8:07:59 PM: warning " > babel-loader@8.0.6" has unmet peer dependency "webpack@>=2".
8:07:59 PM: warning "gatsby > @pmmmwh/react-refresh-webpack-plugin@0.3.1" has incorrect peer dependency "react-refresh@^0.8.2".
8:07:59 PM: warning "gatsby > @typescript-eslint/eslint-plugin > tsutils@3.17.1" has unmet peer dependency "typescript@>=2.8.0 || >= 3.2.0-dev || >= 3.3.0-dev || >= 3.4.0-dev || >= 3.5.0-dev || >= 3.6.0-dev || >= 3.6.0-beta || >= 3.7.0-dev || >= 3.7.0-beta".
8:07:59 PM: warning " > gatsby-link@2.2.27" has unmet peer dependency "@reach/router@^1.1.1".
8:07:59 PM: warning "gatsby-plugin-favicon > favicons-webpack-plugin@0.0.9" has unmet peer dependency "webpack@^1.13.0 || ^2.0.0 || ^3.0.0 || ^4.0.0".
8:07:59 PM: warning "gatsby-plugin-sass > sass-loader@7.3.1" has unmet peer dependency "webpack@^3.0.0 || ^4.0.0".
8:07:59 PM: warning " > gatsby-plugin-styled-components@3.1.16" has unmet peer dependency "babel-plugin-styled-components@>1.5.0".
8:07:59 PM: warning "gatsby-transformer-inline-svg > gatsby > react-hot-loader@4.12.18" has unmet peer dependency "@types/react@^15.0.0 || ^16.0.0".
8:07:59 PM: warning "gatsby-transformer-inline-svg > gatsby > gatsby-cli > ink@2.6.0" has unmet peer dependency "@types/react@>=16.8.0".
8:07:59 PM: warning " > lodash-webpack-plugin@0.11.5" has unmet peer dependency "webpack@^2.0.0 || ^3.0.0 || ^4.0.0".
8:07:59 PM: warning " > react-dates@20.3.0" has unmet peer dependency "moment@^2.18.1".
8:07:59 PM: warning " > react-dates@20.3.0" has unmet peer dependency "react-with-direction@^1.3.0".
8:07:59 PM: warning "react-dates > react-moment-proptypes@1.7.0" has unmet peer dependency "moment@>=1.6.0".
8:07:59 PM: warning "react-stripe-menu > react-scripts > @typescript-eslint/eslint-plugin@1.6.0" has unmet peer dependency "typescript@*".
8:07:59 PM: warning "react-stripe-menu > react-scripts > @typescript-eslint/parser@1.6.0" has unmet peer dependency "typescript@*".
8:07:59 PM: warning "react-stripe-menu > react-scripts > @typescript-eslint/eslint-plugin > @typescript-eslint/typescript-estree@1.6.0" has unmet peer dependency "typescript@*".
8:07:59 PM: warning " > eslint-config-airbnb@18.0.1" has unmet peer dependency "eslint-plugin-react-hooks@^1.7.0".
8:09:58 PM: [4/4] Building fresh packages...
8:10:32 PM: Done in 237.08s.
8:10:32 PM: NPM modules installed using Yarn
```

When combined with netlify/build#1137 this leads to significantly increased build times.

**Comment by verythorough** [comment] 2020-06-06 00:41
Marking this as `type: bug` because it predates Build Plugins work.

**Comment by JGAntunes** [comment] 2021-02-11 13:26
👋 Hey folks, I'm trying to pinpoint some of the reported issues around `yarn` usage and caching problems. There seem to be two big groups of reports:
* Monorepo support (`yarn workspaces` and `lerna` repos) - the directory structure still poses a problem to the way we cache things.
* For a regular "non-monorepo" project, `yarn install` re-installs all the packages when no changes were performed.

I'm assuming this report is about the latter. If so I'm having some trouble reproducing this, and maybe someone could help me out. @jlengstorf I know it was a while back but maybe you can tell me if my assumptions above are correct and if so, do you have any examples of this issue I can look into? I've setup a quick `gatsby` project from a template - https://github.com/JGAntunes/gatsby-yarn-netlify-test - it has a `yarn.lock` file, but after the first run to setup all the dependencies, further executions don't trigger whole `yarn install`s - i.e. https://app.netlify.com/sites/gatsby-yarn-test/deploys/60252f74ca3c3a0007ca0af2 - am I missing something here?

**Comment by JGAntunes** [comment] 2021-02-24 13:40
I'm closing this in favour of #432 and #479 as I'm assuming this is a bug report about `yarn` usage with  `workspaces`. Again do let me know if that is not the case and we can re-open it  🙏

**Closed as completed by JGAntunes** 2021-02-24 13:40 UTC
Labels: feat/builds, type: bug, project/speedy-builds
