### ISSUE TITLE
Building a Gatsby site with Yarn 1.0 results in ton of importing errors

### ISSUE THREAD

**Issue by Aleksion** [netlify/build-image#89] opened 2017-10-09 21:20 UTC
Hi,

I've been fighting a bit with getting GatsbyJS working on Netlify. The root issues is in gatsby: https://github.com/gatsbyjs/gatsby/issues/2001#issuecomment-334796101
Which is caused due to GatsbyJS using a global graphql. Meaning this isn't an error on your end.

As can be seen in the issue, the suggested solution is to use Yarn resolutions and force every yarn dependency to resolve to the same version.

However, I haven't been able to get Yarn 1.0 to run succesfully. Whenever I try to build it stumbles over a new missing dependency in the build flow:

<img width="1181" alt="screen shot 2017-10-09 at 22 59 46" src="https://user-images.githubusercontent.com/3367641/31358402-bccab9f6-ad45-11e7-92ea-a87a1ac92bd8.png">
<img width="1187" alt="screen shot 2017-10-09 at 22 59 56" src="https://user-images.githubusercontent.com/3367641/31358399-bcc4b6fa-ad45-11e7-90e8-a4c814b2bc2f.png">
<img width="1187" alt="screen shot 2017-10-09 at 23 00 10" src="https://user-images.githubusercontent.com/3367641/31358400-bcc856b6-ad45-11e7-8100-932d5350dc67.png">
<img width="1182" alt="screen shot 2017-10-09 at 23 00 21" src="https://user-images.githubusercontent.com/3367641/31358404-bcdba220-ad45-11e7-96d6-46f264984d0a.png">
<img width="1179" alt="screen shot 2017-10-09 at 23 00 32" src="https://user-images.githubusercontent.com/3367641/31358401-bcc99b3e-ad45-11e7-966c-61b24a11125e.png">
<img width="1173" alt="screen shot 2017-10-09 at 23 00 46" src="https://user-images.githubusercontent.com/3367641/31358403-bccc2b1a-ad45-11e7-9b71-56724a679730.png">

UPDATE: 
I've tried to reproduce it with a new starter gatsby project without luck. I'll keep digging on my end of things, but if you have any ideas I'm all ears

**Comment by fool** [comment] 2017-10-09 21:41
for our troubleshooting: similar report from another customer: https://app.intercom.io/a/apps/q245f50x/respond/inbox/1479299/conversations/12192293322

**Comment by fool** [comment] 2017-10-12 20:25
Netlify Support todo:

- get a simpler reproduction case by:
  - create a site using workspaces with 1 dependency
  - add a second dependency in a subdir/package.json and confirm fail
  - build with a cleared cache and confirm success
  - update this bug

**Comment by fool** [comment] 2017-10-17 20:34
We were unable to get a simpler example that we could try debugging, @Aleksion - if you come up with a repro case that is less involved, let us know and we'll reopen this.

**Comment by Aleksion** [comment] 2017-10-18 09:24
Sounds good. I'll dive into it the next time I hit it!

**Comment by jquense** [comment] 2017-10-31 19:43
arg this is a really magical bug :/ I can't manage to put a simpler repro together but this fails consistency on every gatsby netlify deploy when we try with workspaces. Myself and @KyleAMathews independently confirm it does not occur running the docker image locally, or in any other context _except_ for an actual deploy. We've tried changing the versions of node and yarn to no effect and i see no information about this error anywhere:

https://app.netlify.com/sites/using-wordpress/deploys/59f8d06ddf995350b4b3712a

**Comment by fool** [comment] 2017-10-31 21:48
when you run the docker image locally, do you follow the steps to run with
cache just about the 'Contributing' section in README.md?  If not - and if
you don't also set all your environment variables like this:

```
test-tools/test-build.sh path/to/your/repo 'export VAR1=value ; export
VAR2=value2 ; your build command'
```

(and then run it again with the `export T=tmp/tmp.XXXXX` in there as well
to get the cache setup)

**Comment by jquense** [comment] 2017-11-01 01:20
As is usually the case, just after posting I figures it out. The problem is that the default YARN_FLAGS ignores optional deps which for some reason doesn't play nice with workspaces with some packages with post install scripts. Still not sure why I can't reproduce the issue with docker locally tho

**Comment by fool** [comment] 2017-11-01 15:24
so - what YARN_FLAGS do work?  We'll want to write some documentation
around that once we understand your solution :)

**Comment by jquense** [comment] 2017-11-01 15:29
I am not sure why `--ignore-optional` doesn't work in some cases, but it doesn't seem safe as a default. Clearing that, fixed the problem. 

As an aside I do think better defaults for YARN_FLAGS should include `--pure-lockfile` or `--frozen-lockfile` Yarn recommends `--frozen-lockfile` for CI builds but it's a bit opinionated

**Comment by oskarrough** [comment] 2018-01-16 11:35
Can confirm that setting `YARN_FLAGS='--no-ignore-optional` solves it.

I get the error when `YARN_VERSION` is set and `node-sass` is used. I assume it's something with node-sass's postinstall hook + optional dependencies?

Can we change the defaults ala what @jquense suggests and maybe finally update the default Yarn version as well? :) https://github.com/netlify/build-image/issues/122

**Comment by brycekahle** [comment] 2018-02-06 00:06
Yarn finally updated in #130. I'll close this issue when the new image has been deployed.

**Comment by Bouncey** [comment] 2018-02-14 23:24
I'm guessing the new image was deployed within the last 24 hours? Our CSS just broke on a gatsby site

**Comment by brycekahle** [comment] 2018-02-14 23:27
Yes, my apologies. We deployed yesterday afternoon. @Bouncey if you reach out to support, they can help solve your problem.

**Closed by brycekahle** 2018-02-14 23:27 UTC
Labels: needs-review
