### ISSUE TITLE
Builds failing with a Ruby error. 

### ISSUE THREAD

**Issue by depadiernos** [netlify/build-image#245] opened 2019-01-03 13:27 UTC
Recent builds are failing with the following error:

```
5:00:32 AM: ERROR:  Error installing bundler:
5:00:32 AM: 	bundler requires RubyGems version >= 3.0.0. Try 'gem update --system' to update RubyGems itself.
5:00:32 AM: Error installing bundler
```

This also affects builds that don't use Ruby at all.

Possible fix is to update default Ruby version to 2.6.0 here: https://github.com/netlify/build-image/blob/master/run-build-functions.sh#L282

**Comment by rybit** [comment] 2019-01-03 22:02
for the time being, we aren't going to support ruby 2.2 because of the update to bundler. That seems reasonable b/c it was decommissioned back in June. 

The default for our system is 2.3.6 (which has until March iirc). Please reach out to support if this is a large problem. 

Closing for the time being.

**Closed by rybit** 2019-01-03 22:02 UTC

**Comment by TheRickTM** [comment] 2019-01-03 22:12
@rybit this is a problem with the default settings. We aren't using ruby in our project, but because of the docker image installing it, we needed to define the `RUBY_VERSION` in the environment variables for it to build properly, overriding the default.

**Comment by nryoung** [comment] 2019-01-03 22:13
> The default for our system is 2.3.6 (which has until March iirc). Please reach out to support if this is a large problem.


@rybit We ran in to this issue where the Ruby version was defaulting to 2.2.3 even though we don't set it anywhere in our env (our app is not a Ruby app). It was causing our builds to fail.

<img width="1144" alt="screen shot 2019-01-03 at 3 10 22 pm" src="https://user-images.githubusercontent.com/1323750/50664327-e802ef80-0f69-11e9-9eb4-af72bea68132.png">

It would be nice to at least explicitly set the Ruby version to the default that bundler supports or figure out the root cause of the above issue.

**Comment by rybit** [comment] 2019-01-03 23:04
so we just updated this to not be that version any longer. The default should be 2.3.6 when you don't explicitly set it

**Comment by nryoung** [comment] 2019-01-03 23:18
@rybit 	Whatever y'all changed our builds are now installing `2.3.6` without the `RUBY_VERSION` env set. Thanks!

**Comment by krzychukula** [comment] 2021-09-18 19:20
I'm not sure why but I got caught by this. My build was failing and I wasn't using under in the first place. 
Switching to Ubuntu 16 resolves it. 

> 9:10:21 PM: /opt/buildhome/.rvm/scripts/override_gem: line 19: gem: command not found
> 9:10:21 PM: Error installing bundler
> 9:10:21 PM: Build was terminated: Build script returned non-zero exit code: 1
