### ISSUE TITLE
Could not find 'bundler' (2.0.2)

### ISSUE THREAD

**Issue by igoynawamreh** [netlify/build-image#328] opened 2019-08-05 03:34 UTC
Jekyll deployment with bundler `v2.0.1` works fine.

I'm trying to update bundler to `v2.0.2`, I get this error:

```
9:55:36 AM: Build ready to start
9:55:38 AM: build-image version: 9e0f207a27642d0115b1ca97cd5e8cebbe492f63
9:55:38 AM: build-image tag: v3.3.2
9:55:38 AM: buildbot version: ef8d0929ed0baabafd8bbb7d0b021e1fc24180c0
9:55:39 AM: Fetching cached dependencies
9:55:39 AM: Starting to download cache of 119.4MB
9:55:39 AM: Finished downloading cache in 908.054542ms
9:55:39 AM: Starting to extract cache
9:55:43 AM: Finished extracting cache in 3.867926401s
9:55:43 AM: Finished fetching cache in 4.835648508s
9:55:43 AM: Starting to prepare the repo for build
9:55:44 AM: Preparing Git Reference refs/heads/master
9:55:45 AM: Starting build script
9:55:45 AM: Installing dependencies
9:55:45 AM: Started restoring cached node version
9:55:49 AM: Finished restoring cached node version
9:55:50 AM: v10.16.1 is already installed.
9:55:51 AM: Now using node v10.16.1 (npm v6.9.0)
9:55:51 AM: Attempting ruby version 2.6.2, read from environment
9:55:52 AM: Using ruby version 2.6.2
9:55:52 AM: Using PHP version 5.6
9:55:52 AM: Started restoring cached ruby gems
9:55:52 AM: Finished restoring cached ruby gems
9:55:52 AM: Installing gem bundle
9:55:53 AM: Warning: the running version of Bundler (2.0.1) is older than the version that created the lockfile (2.0.2). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
9:55:55 AM: Fetching gem metadata from https://rubygems.org/
9:55:55 AM: .
9:55:55 AM: .
9:55:55 AM: .
9:55:55 AM: .
9:55:56 AM: .
9:55:56 AM: .
9:55:56 AM: .
9:55:56 AM: .
9:55:56 AM: .
9:55:56 AM: .
9:55:56 AM: .
9:55:57 AM: Fetching public_suffix 3.1.1
9:55:57 AM: Installing public_suffix 3.1.1
9:55:57 AM: Using addressable 2.6.0
9:55:57 AM: Using bundler 2.0.1
9:55:57 AM: Using colorator 1.1.0
9:55:57 AM: Using concurrent-ruby 1.1.5
9:55:57 AM: Using eventmachine 1.2.7
9:55:57 AM: Using http_parser.rb 0.6.0
9:55:57 AM: Using em-websocket 0.5.1
9:55:57 AM: Using ffi 1.11.1
9:55:57 AM: Using forwardable-extended 2.6.0
9:55:57 AM: Using i18n 0.9.5
9:55:57 AM: Using rb-fsevent 0.10.3
9:55:57 AM: Using rb-inotify 0.10.0
9:55:57 AM: Using sass-listen 4.0.0
9:55:57 AM: Using sass 3.7.4
9:55:57 AM: Using jekyll-sass-converter 1.5.2
9:55:57 AM: Using ruby_dep 1.5.0
9:55:57 AM: Using listen 3.1.5
9:55:57 AM: Using jekyll-watch 2.2.1
9:55:57 AM: Using kramdown 1.17.0
9:55:57 AM: Using liquid 4.0.3
9:55:57 AM: Using mercenary 0.3.6
9:55:57 AM: Using pathutil 0.16.2
9:55:57 AM: Fetching rouge 3.7.0
9:55:57 AM: Installing rouge 3.7.0
9:55:57 AM: Using safe_yaml 1.0.5
9:55:57 AM: Fetching jekyll 3.8.6
9:55:57 AM: Installing jekyll 3.8.6
9:55:58 AM: Using jekyll-paginate-v2 2.0.0
9:55:58 AM: Using jekyll-redirect-from 0.15.0
9:55:58 AM: Using jekyll-sitemap 1.1.1
9:55:58 AM: Bundle complete! 4 Gemfile dependencies, 29 gems now installed.
9:55:58 AM: Bundled gems are installed into `/opt/build/cache/bundle`
9:55:58 AM: Gem bundle installed
9:55:58 AM: Started restoring cached go cache
9:55:58 AM: Finished restoring cached go cache
9:55:58 AM: unset GOOS;
9:55:58 AM: unset GOARCH;
9:55:58 AM: export GOROOT='/opt/buildhome/.gimme/versions/go1.12.linux.amd64';
9:55:58 AM: export PATH="/opt/buildhome/.gimme/versions/go1.12.linux.amd64/bin:${PATH}";
9:55:58 AM: go version >&2;
9:55:58 AM: export GIMME_ENV='/opt/buildhome/.gimme/env/go1.12.linux.amd64.env';
9:55:58 AM: go version go1.12 linux/amd64
9:55:58 AM: Installing missing commands
9:55:58 AM: Verify run directory
9:55:58 AM: Executing user command: jekyll build
9:55:58 AM: Activating bundler (2.0.2) failed:
9:55:58 AM: Could not find 'bundler' (2.0.2) required by your /opt/build/repo/Gemfile.lock.
9:55:58 AM: To update to the latest version installed on your system, run `bundle update --bundler`.
9:55:58 AM: To install the missing version, run `gem install bundler:2.0.2`
9:55:58 AM: Checked in 'GEM_PATH=/opt/buildhome/.rvm/gems/ruby-2.6.2:/opt/buildhome/.rvm/rubies/ruby-2.6.2/lib/ruby/gems/2.6.0', execute `gem env` for more information
9:55:58 AM: To install the version of bundler this project requires, run `gem install bundler -v '2.0.2'`
9:55:58 AM: Skipping functions preparation step: no functions directory set
9:55:58 AM: Caching artifacts
9:55:58 AM: Started saving ruby gems
9:55:58 AM: Finished saving ruby gems
9:55:58 AM: Started saving pip cache
9:55:58 AM: Finished saving pip cache
9:55:58 AM: Started saving emacs cask dependencies
9:55:58 AM: Finished saving emacs cask dependencies
9:55:58 AM: Started saving maven dependencies
9:55:58 AM: Finished saving maven dependencies
9:55:58 AM: failed during stage 'building site': Build script returned non-zero exit code: 42
9:55:58 AM: Started saving boot dependencies
9:55:58 AM: Finished saving boot dependencies
9:55:58 AM: Started saving go dependencies
9:55:58 AM: Finished saving go dependencies
9:55:58 AM: Error running command: Build script returned non-zero exit code: 42
9:55:58 AM: Failing build: Failed to build site
9:55:58 AM: Finished processing build request in 19.831067385s
```

**Comment by overlordofmu** [comment] 2019-08-06 02:21
@igoynawamreh, I believe this is a duplicate of the following issue:

https://github.com/netlify/build-image/issues/296

Because there is an existing issue which covers this, I'm closing this issue to track it there.

**Closed as completed by overlordofmu** 2019-08-06 02:21 UTC
Labels: duplicate
